### ISSUE TITLE
Mods folder location

### ISSUE THREAD

**Issue by mag1c22** [marc0x1/pokemmo-flatpak-manifest#3]
Hello, where is the mods folder so I can install mods for Pokemmo?  

Thanks!

**Comment by marc0x1** [comment]
You can find it inside pokemmo gui:
`Mod management -> Open Mods Folder`
or with a file manager:
`/home/$USER/.var/app/io.github.pokemmo/data/PokeMMO-Client/data/mods`
If you like this package feel free to upvote this thread on the pokemmo forum:
https://forums.pokemmo.com/index.php?/topic/153979-pokemmo-flatpak/
